spring:
  application:
    name: omnidrive

server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://raspberrypi:8761/eureka/

logging:
  level:
    com.pro.jenova.omnidrive.rest.filter.RequestAndResponseLogger: DEBUG