spring:
  application:
    name: omnidrive

  datasource:
    url: jdbc:mysql://cronos:3306/omnidrive?useUnicode=true&serverTimezone=UTC
    username: dimitrios
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.xml

  rabbitmq:
    host: cronos
    port: 5672
    username: admin
    password: admin

  cloud:
    refresh:
      enabled: false # FIXME: This needs to be removed once issue is fixed (bug with circular dependency).

server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://deepwater:8761/eureka/

---
spring:
  profiles: h2

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect