spring:
  application:
    name: omnidrive

  datasource:
    url: #jdbc:h2:~/omnidrive;DB_CLOSE_ON_EXIT=FALSE
    username:
    password:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: org.h2.Driver

    tomcat:
      max-wait: 30000
      max-active: 20
      max-idle: 20
      min-idle: 10
      initial-size: 10
      test-on-borrow: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

liquibase:
  change-log: classpath:liquibase/changelog-master.xml

server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.178.56:8761/eureka/

management:
  security:
    enabled: false