spring:
  application:
    name: omnidrive

  datasource:
    url: jdbc:mysql://cronos:3306/jenova_db
    username: dimitrios
    password: password
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver

    tomcat:
      max-wait: 30000
      max-active: 20
      max-idle: 20
      min-idle: 10
      initial-size: 10
      test-on-borrow: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none

liquibase:
  change-log: classpath:liquibase/changelog-master.xml

server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://netrunner-01:8761/eureka/

management:
  security:
    enabled: false