spring:
  application:
    name: omnidrive

  datasource:
    url: #jdbc:h2:~/omnidrive;DB_CLOSE_ON_EXIT=FALSE
    username:
    password:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: org.h2.Driver

    tomcat:
      max-wait: 5000
      max-active: 10
      test-on-borrow: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://skyline:8000/eureka/

# Actuator Configuration
endpoints:
  shutdown:
    enabled: true
    sensitive: false