spring:
  application:
    name: omnidrive

server:
  port: 8091

endpoints:
  shutdown:
    enabled: true
    sensitive: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://raspberrypi:8761/eureka/
