spring:
  application:
    name: omnidrive

  datasource:
    url: jdbc:mariadb://cronos:3306/omnidrive?useUnicode=true&serverTimezone=UTC
    username: dimitrios
    password: password
    driver-class-name: org.mariadb.jdbc.Driver

    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.xml

  rabbitmq:
    host: cronos
    port: 5672
    username: admin
    password: admin

security:
  oauth2:
    resource:
      client-id: trusted-client
      client-secret: trusted-client
      token-info-uri: http://deepwater:8090/jenova/oauth/check_token

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8001

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 4
    leaseExpirationDurationInSeconds: 10
  client:
    registryFetchIntervalSeconds: 3
    shouldDisableDelta: true
    serviceUrl:
      defaultZone: http://deepwater:8761/eureka/

---
spring:
  profiles: local

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8090/jenova/oauth/check_token