spring:
  application:
    name: exodus

  rabbitmq:
    host: cronos
    port: 5672
    username: admin
    password: admin

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://deepwater:8761/eureka/
