spring:
  application:
    name: hyperion

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8091

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 4
    leaseExpirationDurationInSeconds: 10
  client:
    registryFetchIntervalSeconds: 3
    shouldDisableDelta: true
    serviceUrl:
      defaultZone: http://deepwater:8761/eureka/
