spring:
  application:
    name: hyperion

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://deepwater:8761/eureka/

