filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/log/earthrise.log
  multiline.pattern: '^[[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}'
  multiline.negate: true
  multiline.match: after

output.logstash:
  hosts: ["cronos:5044"]
