filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/log/jenova/*.log
  json.keys_under_root: true
  json.overwrite_keys: false
  json.add_error_key: true

output.elasticsearch:
  hosts: ["http://cronos:9200"]
