- hosts: earthrise
  tasks:
  - name: ensure base packages are installed
    become: true
    apt: name={{ item }} state=installed
    with_items:
      - openjdk-8-jdk
      - whois
      - curl
  - name: ensure log shipper is installed
    become: true
    apt:
      deb: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.2.4-amd64.deb
  - name: ensure appropriate group exists
    become: true
    group:
      name: earthrise
      state: present
  - name: ensure appropriate user exists
    become: true
    user:
      name: earthrise
      password: '$6$i37xBhfw$sovtpYT/XfbjezSU1wxKUWo/WwICusd47S.vMoArqK/RkXZzxWxynMsKA9YqjBmt/T88ACgPzrgx18WRP0zBD0'
      group: earthrise
  - name: create artifacts directory where the package will be copied into
    become: true
    file:
      path: "/opt/earthrise_tmp"
      state: directory
  - name: upload package binary into artifacts directory
    become: true
    copy:
      src: "{{playbook_dir}}/../../earthrise/build/distributions/earthrise_{{version}}_all.deb"
      dest: "/opt/earthrise_tmp/earthrise_{{version}}.deb"
  - name: check if service being installed exists from before
    become: true
    stat:
      path: "/etc/init.d/earthrise"
    register: service_status
  - name: if service being installed exists, then make sure it is stopped
    become: true
    service:
      name: earthrise
      state: stopped
    when: service_status.stat.exists
  - name: uninstall package of interest if already installed from before
    become: true
    apt:
      name: earthrise
      state: absent
  - name: install uploaded package
    become: true
    apt:
      deb: "/opt/earthrise_tmp/earthrise_{{version}}.deb"
  - name: start service that was installed
    become: true
    service:
      name: earthrise
      state: started
      enabled: true
  - name: clean up artifacts directory
    become: true
    file:
      path: "/opt/earthrise_tmp"
      state: absent

- hosts: omnidrive
  tasks:
  - name: ensure base packages are installed
    become: true
    apt: name={{ item }} state=installed
    with_items:
      - openjdk-8-jdk
      - whois
      - curl
  - name: ensure appropriate group exists
    become: true
    group:
      name: omnidrive
      state: present
  - name: ensure appropriate user exists
    become: true
    user:
      name: omnidrive
      password: '$6$ELgYiHpQ3$9QZY2z.uVb2eSR7x0ZRcMYZT.4Ko.CNwAqyJRg9essVpRMvAuGdsXYbPGexVvzqYPlnakP2YJ9gfFDAMnDEkv1'
      group: omnidrive
  - name: create artifacts directory where the package will be copied into
    become: true
    file:
      path: "/opt/omnidrive_tmp"
      state: directory
  - name: upload package binary into artifacts directory
    become: true
    copy:
      src: "{{playbook_dir}}/../../omnidrive/build/distributions/omnidrive_{{version}}_all.deb"
      dest: "/opt/omnidrive_tmp/omnidrive_{{version}}.deb"
  - name: check if service being installed exists from before
    become: true
    stat:
      path: "/etc/init.d/omnidrive"
    register: service_status
  - name: if service being installed exists, then make sure it is stopped
    become: true
    service:
      name: omnidrive
      state: stopped
    when: service_status.stat.exists
  - name: uninstall package of interest if already installed from before
    become: true
    apt:
      name: omnidrive
      state: absent
  - name: install uploaded package
    become: true
    apt:
      deb: "/opt/omnidrive_tmp/omnidrive_{{version}}.deb"
  - name: start service that was installed
    become: true
    service:
      name: omnidrive
      state: started
      enabled: true
  - name: clean up artifacts directory
    become: true
    file:
      path: "/opt/omnidrive_tmp"
      state: absent
