- hosts: earthrise
  tasks:
  - name: create artifacts directory where the packages to be installed will be copied into
    become: true
    file:
      path: "/opt/artifacts"
      state: directory
  - name: upload package to be installed into artifacts directory
    become: true
    copy:
      src: "{{playbook_dir}}/../../earthrise/build/distributions/earthrise_{{version}}_all.deb"
      dest: "/opt/artifacts/earthrise_{{version}}.deb"
  - name: remove any existing installation of uploaded package
    become: true
    apt:
      name: earthrise
      state: absent
  - name: stop any previous service execution of the package being installed
    become: true
    service:
      name: earthrise
      state: stopped
  - name: install uploaded package
    become: true
    apt:
      deb: "/opt/artifacts/earthrise_{{version}}.deb"
  - name: start service execution of the package that was installed
    become: true
    service:
      name: earthrise
      state: started
  - name: clean up artifacts directory once installation is complete
    become: true
    file:
      path: "/opt/artifacts"
      state: absent
