- hosts: earthrise
  tasks:
  - name: create artifacts directory where the packages to be installed will be copied into
    become: true
    file:
      path: "/opt/artifacts"
      state: directory
  - name: upload package to be installed into artifacts directory
    become: true
    copy:
      src: "{{playbook_dir}}/../../earthrise/build/distributions/earthrise_{{version}}_all.deb"
      dest: "/opt/artifacts/earthrise_{{version}}.deb"
  - name: check if the service associated with the package being installed exists from before
    become: true
    stat:
      path: "/etc/init.d/earthrise"
    register: service_status
  - name: stop any previous service execution of the package being installed
    become: true
    service:
      name: earthrise
      state: stopped
    when: service_status.stat.exists
  - name: remove any existing installation of uploaded package
    become: true
    apt:
      name: earthrise
      state: absent
  - name: install uploaded package
    become: true
    apt:
      deb: "/opt/artifacts/earthrise_{{version}}.deb"
  - name: start service execution of the package that was installed
    become: true
    service:
      name: earthrise
      state: started
  - name: clean up artifacts directory once installation is complete
    become: true
    file:
      path: "/opt/artifacts"
      state: absent
