- hosts: earthrise
  tasks:
  - name: create artifacts directory
    become: true
    file:
      path: "/opt/artifacts/earthrise"
      state: directory
  - name: upload to artifacts directory
    become: true
    copy:
      src: "{{playbook_dir}}/../../earthrise-deb/build/distributions/earthrise-deb_{{version}}_all.deb"
      dest: "/opt/artifacts/earthrise/earthrise-deb_{{version}}_all.deb"
  - name: remove existing package
    become: true
    apt:
      name: earthrise-deb
      state: absent
  - name: install uploaded package
    become: true
    apt:
      deb: "/opt/artifacts/earthrise/earthrise-deb_{{version}}_all.deb"

- hosts: omnidrive
  tasks:
  - name: create artifacts directory
    become: true
    file:
      path: "/opt/artifacts/omnidrive"
      state: directory
  - name: upload to artifacts directory
    become: true
    copy:
      src: "{{playbook_dir}}/../../omnidrive-deb/build/distributions/omnidrive-deb_{{version}}_all.deb"
      dest: "/opt/artifacts/omnidrive/omnidrive-deb_{{version}}_all.deb"
  - name: remove existing package
    become: true
    apt:
      name: omnidrive-deb
      state: absent
  - name: install uploaded package
    become: true
    apt:
      deb: "/opt/artifacts/omnidrive/omnidrive-deb_{{version}}_all.deb"
