- hosts: earthrise
  tasks:
  - name: create artifacts directory where the package will be copied into
    become: true
    file:
      path: "/opt/earthrise_tmp"
      state: directory
  - name: upload package binary into artifacts directory
    become: true
    copy:
      src: "{{playbook_dir}}/../../earthrise/build/distributions/earthrise_{{version}}_all.deb"
      dest: "/opt/earthrise_tmp/earthrise_{{version}}.deb"
  - name: check if service being installed exists from before
    become: true
    stat:
      path: "/etc/init.d/earthrise"
    register: service_status
  - name: if service being installed exists, then make sure it is stopped
    become: true
    service:
      name: earthrise
      state: stopped
    when: service_status.stat.exists
  - name: uninstall package of interest if already installed from before
    become: true
    apt:
      name: earthrise
      state: absent
  - name: install uploaded package
    become: true
    apt:
      deb: "/opt/earthrise_tmp/earthrise_{{version}}.deb"
  - name: start service that was installed
    become: true
    service:
      name: earthrise
      state: started
      enabled: true
  - name: clean up artifacts directory
    become: true
    file:
      path: "/opt/earthrise_tmp"
      state: absent
