- hosts: earthrise
  tasks:
  - name: create directory for artifacts
    become: true
    file:
      path: /opt/artifacts/earthrise"
      state: directory
  - name: copy artifact to directory
    become: true
    copy:
      src: ./earthrise-deb/build/distributions/earthrise-deb_{{version}}_all.deb
      dest: /opt/artifacts/earthrise
