- hosts: earthrise
  tasks:
  - name: create artifacts directory
    become: true
    file:
      path: "/opt/artifacts/earthrise"
      state: directory
  - name: upload to artifacts directory
    become: true
    copy:
      src: "{{playbook_dir}}/../../earthrise-deb/build/distributions/earthrise-deb_{{version}}_all.deb"
      dest: "/opt/artifacts/earthrise/earthrise-deb_{{version}}_all.deb"
  - name: install uploaded package
    become: true
    apt:
      deb: "/opt/artifacts/earthrise/earthrise-deb_{{version}}_all.deb"
