spring:
  application:
    name: gatekeeper

zuul:
  ignoredServices: '*'
  prefix: /jenova
  routes:
    user:
      path: /user/**
      serviceId: justitia
      strip-prefix: false
    authority:
      path: /authority/**
      serviceId: justitia
      strip-prefix: false

server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://deepwater:8761/eureka/

