spring:
  application:
    name: gatekeeper

zuul:
  ignoredServices: '*'
  prefix: /jenova
  routes:
    user:
      path: /user/**
      serviceId: omnidrive
      strip-prefix: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10

server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://netrunner-01:8761/eureka/

management:
  security:
    enabled: false
