spring:
  application:
    name: gatekeeper

zuul:
  ignoredServices: '*'
  prefix: /jenova
  routes:
    user:
      path: /user/**
      sensitiveHeaders:
      serviceId: justitia
    authority:
      path: /authority/**
      sensitiveHeaders:
      serviceId: justitia
    echo:
      path: /echo/**
      sensitiveHeaders:
      serviceId: omnidrive

server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://deepwater:8761/eureka/

