spring:
  application:
    name: gatekeeper

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://deepwater:8761/eureka/

zuul:
  ignoredServices: '*'
  prefix: /jenova
  routes:
    oauth:
      path: /oauth/**
      sensitiveHeaders:
      serviceId: justitia
      stripPrefix: false
    justitia-api:
      path: /justitia-api/**
      sensitiveHeaders:
      serviceId: justitia
      stripPrefix: false
    omnidrive-api:
      path: /omnidrive-api/**
      sensitiveHeaders:
      serviceId: omnidrive
      stripPrefix: false