spring:
  application:
    name: gatekeeper

zuul:
  prefix: /jenova

server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://netrunner-01:8761/eureka/

management:
  security:
    enabled: false