spring:
  application:
    name: gatekeeper

zuul:
  ignoredServices: '*'
  prefix: /jenova
  routes:
    user:
      path: /user/**
      sensitiveHeaders:
      serviceId: justitia
      stripPrefix: false
    authority:
      path: /authority/**
      sensitiveHeaders:
      serviceId: justitia
      stripPrefix: false
    echo:
      path: /echo/**
      sensitiveHeaders:
      serviceId: omnidrive
      stripPrefix: false

server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://deepwater:8761/eureka/

