spring:
  application:
    name: gatekeeper

zuul:
  ignoredServices: '*'
  prefix: /jenova
  routes:
    user:
      path: /user/**
      serviceId: omnidrive
      strip-prefix: false

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 90000

server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://deepwater:8761/eureka/

