spring:
  application:
    name: earthrise-eureka

# Eureka Server Configuration
server:
  port: 8000

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

# Actuator Configuration
endpoints:
  shutdown:
    enabled: true
    sensitive: false