spring:
  application:
    name: earthrise

server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.178.56
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.ip-address}:${server.port}/eureka

management:
  security:
    enabled: false