spring:
  application:
    name: earthrise

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8761

eureka:
  numberRegistrySyncRetries: 1
  instance:
    hostname: deepwater
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: true
