spring:
  application:
    name: earthrise

server:
  port: 8761

eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://192.168.178.59:${server.port}/eureka/


management:
  security:
    enabled: false