spring:
  application:
    name: earthrise

server:
  port: 8761

endpoints:
  shutdown:
    enabled: true
    sensitive: false

eureka:
  instance:
    hostname: localhost
  server:
    enableSelfPreservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
