spring:
  application:
    name: earthrise

# Eureka Server Configuration
server:
  port: 8000

eureka:
  instance:
    hostname: lnv-pc
  server:
    enableSelfPreservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

# Actuator Configuration
endpoints:
  shutdown:
    enabled: true
    sensitive: false