spring:
  application:
    name: earthrise

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000
    responseCacheUpdateIntervalMs: 3000

---
spring:
  profiles: local